# Generated by Django 4.1.1 on 2023-06-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('slider', 'Slider'), ('card', 'Card'), ('testimonial', 'Testimonial'), ('gallery', 'Gallery')], max_length=20),
        ),
    ]
