# Generated by Django 4.1.1 on 2023-06-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_post_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('slider', 'Slider'), ('card', 'Card'), ('testimonial', 'Testimonial'), ('gallery', 'Gallery'), ('galleryimages', 'Galleryimages'), ('aboutus', 'Aboutus'), ('aboutimages', 'Aboutimages'), ('contact', 'Contact')], max_length=20),
        ),
    ]
